name: Generate PDFKit WidgetTest

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Run Swift script on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Swift version
        run: swift --version

      - name: Run PDFKit script
        run: |
          swift CreatePDFWidgets.swift
          ls -lh WidgetTest.pdf

      - name: Upload WidgetTest.pdf
        uses: actions/upload-artifact@v2.3.2
        with:
          name: WidgetTest-pdf
          path: WidgetTest.pdf
