name: Generate PDFKit WidgetTest (Base64 Fallback)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Run Swift script & Emit Base64
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Swift version
        run: swift --version

      - name: Run PDFKit script
        run: |
          swift CreatePDFWidgets.swift
          ls -lh WidgetTest.pdf

      - name: Base64-encode WidgetTest.pdf
        run: |
          echo "===== BEGIN BASE64 WIDGETTEST.PDF ====="
          base64 WidgetTest.pdf
          echo "=====  END BASE64 WIDGETTEST.PDF  ====="
